### ISSUE TITLE
Traceback issue

### ISSUE THREAD

**Issue by phracek** [fedora-modularity/check_modulemd#6]
Well, I have a GitHub repository https://github.com/container-images/memcached/ with the modulemd file. 

Once I run command ```<full_path_to_clone_your_github_repository>/check_modulemd.py```
then I get traceback:

~~~
~/work/programming/container-images/memcached # /home/phracek/work/programming/check_modulemd/check_modulemd.py 
found extension EntryPoint.parse('journal = avocado.plugins.journal:JournalResult')
found extension EntryPoint.parse('tap = avocado.plugins.tap:TAPResult')
found extension EntryPoint.parse('human = avocado.plugins.human:Human')
found extension EntryPoint.parse('jobscripts = avocado.plugins.jobscripts:JobScripts')
Command line: /home/phracek/work/programming/check_modulemd/check_modulemd.py

Avocado version: 43.0

Config files read (in order):
/etc/avocado/avocado.conf
/etc/avocado/conf.d/gdb.conf
/home/phracek/.config/avocado/avocado.conf

Avocado config:
Section.Key                             Value
datadir.paths.base_dir                  /usr/share/avocado
datadir.paths.test_dir                  /usr/share/avocado/tests
datadir.paths.data_dir                  /usr/share/avocado/data
datadir.paths.logs_dir                  ~/avocado/job-results
sysinfo.collect.enabled                 True
sysinfo.collect.installed_packages      False
sysinfo.collect.profiler                False
sysinfo.collect.locale                  C
sysinfo.collectibles.commands           /etc/avocado/sysinfo/commands
sysinfo.collectibles.files              /etc/avocado/sysinfo/files
sysinfo.collectibles.profilers          /etc/avocado/sysinfo/profilers
runner.output.colored                   True
runner.output.utf8                      
runner.behavior.keep_tmp_files          False
remoter.behavior.reject_unknown_hosts   False
remoter.behavior.disable_known_hosts    False
job.output.loglevel                     debug
restclient.connection.hostname          localhost
restclient.connection.port              9405
restclient.connection.username          
restclient.connection.password          
plugins.disable                         []
plugins.skip_broken_plugin_notification []
plugins.loaders                         ['file', '@DEFAULT']
gdb.paths.gdb                           /usr/bin/gdb
gdb.paths.gdbserver                     /usr/bin/gdbserver

Avocado Data Directories:

Avocado replaces config dirs that can't be accessed
with sensible defaults. Please edit your local config
file to customize values

base     /home/phracek/avocado
tests    /home/phracek/avocado/tests
data     /home/phracek/avocado/data
logs     /home/phracek/avocado/job-results

Temporary dir: /tmp/avocado_fQoi0K

Variant 1:    /

Job ID: 423be4b77017e232929637288857bf3a9ce1278f

PARAMS (key=timeout, path=*, default=None) => None
START 01-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_debugdump
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 01-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_debugdump -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 02-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_api
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 02-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_api -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 03-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_components
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 03-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_components -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 04-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_dependencies
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 04-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_dependencies -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 05-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_description
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 05-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_description -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 06-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_description_spelling
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 06-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_description_spelling -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 07-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_summary
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 07-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_summary -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 08-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_summary_spelling
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 08-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_summary_spelling -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 09-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_rationales
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 09-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_rationales -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 10-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_rationales_spelling
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 10-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_rationales_spelling -> TestSetupFail: modulemd parameter must be supplied

PARAMS (key=timeout, path=*, default=None) => None
START 11-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_component_availability
PARAMS (key=modulemd, path=*, default=None) => None

Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:442
Traceback (most recent call last):
  File "/home/phracek/work/programming/check_modulemd/check_modulemd.py", line 28, in setUp
    self.error("modulemd parameter must be supplied")
  File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 623, in error
    raise exceptions.TestError(message)
TestError: modulemd parameter must be supplied

ERROR 11-/home/phracek/work/programming/check_modulemd/check_modulemd.py:ModulemdTest.test_component_availability -> TestSetupFail: modulemd parameter must be supplied

Test results available in /tmp/avocado_avocado.core.jobMvtUw1
~~~

**Comment by phracek** [comment]
It seems, like I run it wrongly. Sorry for the issue
